require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OwnerRequestsController do

  # This should return the minimal set of attributes required to create a valid
  # OwnerRequest. As you add validations to OwnerRequest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OwnerRequestsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all owner_requests as @owner_requests" do
      owner_request = OwnerRequest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:owner_requests).should eq([owner_request])
    end
  end

  describe "GET show" do
    it "assigns the requested owner_request as @owner_request" do
      owner_request = OwnerRequest.create! valid_attributes
      get :show, {:id => owner_request.to_param}, valid_session
      assigns(:owner_request).should eq(owner_request)
    end
  end

  describe "GET new" do
    it "assigns a new owner_request as @owner_request" do
      get :new, {}, valid_session
      assigns(:owner_request).should be_a_new(OwnerRequest)
    end
  end

  describe "GET edit" do
    it "assigns the requested owner_request as @owner_request" do
      owner_request = OwnerRequest.create! valid_attributes
      get :edit, {:id => owner_request.to_param}, valid_session
      assigns(:owner_request).should eq(owner_request)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OwnerRequest" do
        expect {
          post :create, {:owner_request => valid_attributes}, valid_session
        }.to change(OwnerRequest, :count).by(1)
      end

      it "assigns a newly created owner_request as @owner_request" do
        post :create, {:owner_request => valid_attributes}, valid_session
        assigns(:owner_request).should be_a(OwnerRequest)
        assigns(:owner_request).should be_persisted
      end

      it "redirects to the created owner_request" do
        post :create, {:owner_request => valid_attributes}, valid_session
        response.should redirect_to(OwnerRequest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved owner_request as @owner_request" do
        # Trigger the behavior that occurs when invalid params are submitted
        OwnerRequest.any_instance.stub(:save).and_return(false)
        post :create, {:owner_request => { "user_id" => "invalid value" }}, valid_session
        assigns(:owner_request).should be_a_new(OwnerRequest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OwnerRequest.any_instance.stub(:save).and_return(false)
        post :create, {:owner_request => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested owner_request" do
        owner_request = OwnerRequest.create! valid_attributes
        # Assuming there are no other owner_requests in the database, this
        # specifies that the OwnerRequest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OwnerRequest.any_instance.should_receive(:update_attributes).with({ "user_id" => "1" })
        put :update, {:id => owner_request.to_param, :owner_request => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested owner_request as @owner_request" do
        owner_request = OwnerRequest.create! valid_attributes
        put :update, {:id => owner_request.to_param, :owner_request => valid_attributes}, valid_session
        assigns(:owner_request).should eq(owner_request)
      end

      it "redirects to the owner_request" do
        owner_request = OwnerRequest.create! valid_attributes
        put :update, {:id => owner_request.to_param, :owner_request => valid_attributes}, valid_session
        response.should redirect_to(owner_request)
      end
    end

    describe "with invalid params" do
      it "assigns the owner_request as @owner_request" do
        owner_request = OwnerRequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OwnerRequest.any_instance.stub(:save).and_return(false)
        put :update, {:id => owner_request.to_param, :owner_request => { "user_id" => "invalid value" }}, valid_session
        assigns(:owner_request).should eq(owner_request)
      end

      it "re-renders the 'edit' template" do
        owner_request = OwnerRequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OwnerRequest.any_instance.stub(:save).and_return(false)
        put :update, {:id => owner_request.to_param, :owner_request => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested owner_request" do
      owner_request = OwnerRequest.create! valid_attributes
      expect {
        delete :destroy, {:id => owner_request.to_param}, valid_session
      }.to change(OwnerRequest, :count).by(-1)
    end

    it "redirects to the owner_requests list" do
      owner_request = OwnerRequest.create! valid_attributes
      delete :destroy, {:id => owner_request.to_param}, valid_session
      response.should redirect_to(owner_requests_url)
    end
  end

end
